# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Project
mod_id=nirvana
mod_name=Nirvana
mod_author=possible_triangle
mod_version=0.0.0-dev
release_type=release

# Common
mc_version=26.2

# Forge
neoforge_version=26.2

# Fabric
fabric_api_version=0.157.0+26.2
fabric_loader_version=0.19.3

# Publishing
repository=teamgalena/nirvana
maven_group=dev.galena
curseforge_project_id=1278909
modrinth_project_id=7vLeZs9H
