name: Compile

on:
  push:
    branches: ["fix/26.2-compile"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'
      - name: Compile common
        run: ./gradlew :common:compileJava --console=plain
